import { PlanetData } from './types';

export const SUN_DATA = {
  name: 'The Sun',
  diameter: 1392700, // km
  mass: '1.989 x 10^30 kg',
  tempCore: '15,000,000°C',
  tempSurface: '5,500°C',
  gravity: 274, // m/s^2
  description: 'The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.',
  funFacts: [
    'Over one million Earths could fit inside the Sun.',
    'The Sun contains 99.86% of all the mass in the Solar System.',
    'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.'
  ]
};

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    mass: '3.301 x 10^23 kg',
    gravity: 3.7,
    diameter: 4879,
    tempRange: '-173°C to 427°C',
    orbitalPeriod: '87.97 Days',
    rotationPeriod: '58.6 Days',
    distanceFromSun: 0.39,
    realDistanceMillionKm: 57.9,
    moons: [],
    description: 'The smallest planet in our solar system and the closest to the Sun, Mercury is only slightly larger than Earth\'s Moon. It has a cratered, rocky surface resembling a desert.',
    funFacts: [
      'Mercury experiences extreme heat and cold, having no substantial atmosphere to trap heat.',
      'A year on Mercury is just 88 Earth days, but a single day-night cycle takes 176 Earth days!',
      'Despite being closest to the Sun, Venus is hotter than Mercury.'
    ],
    atmosphere: [
      { gas: 'Oxygen', percentage: '42%' },
      { gas: 'Sodium', percentage: '29%' },
      { gas: 'Hydrogen', percentage: '22%' },
      { gas: 'Helium', percentage: '6%' }
    ],
    structure: [
      { name: 'Crust', thickness: '35 km', composition: 'Silicate Rock', color: '#8c8c8c' },
      { name: 'Mantle', thickness: '400 km', composition: 'Solid Silicates', color: '#a6a6a6' },
      { name: 'Core', thickness: '2,020 km', composition: 'Molten Iron and Nickel', color: '#d9d9d9' }
    ],
    color: '#9E9E9E',
    accentColor: '#B0BEC5',
    texturePattern: 'craters',
    orbitalSpeed: 0.04,
    sizeScale: 6,
    realSizeScale: 3.8
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    mass: '4.867 x 10^24 kg',
    gravity: 8.87,
    diameter: 12104,
    tempRange: '462°C (Constant)',
    orbitalPeriod: '224.7 Days',
    rotationPeriod: '243 Days (Retrograde)',
    distanceFromSun: 0.72,
    realDistanceMillionKm: 108.2,
    moons: [],
    description: 'Venus is the second planet from the Sun and our closest planetary neighbor. It is locked in a runaway greenhouse effect, covered in thick layer of yellowish toxic carbon-dioxide atmosphere.',
    funFacts: [
      'Venus rotates backwards in the opposite direction of most other planets (retrograde rotation).',
      'Venus is the hottest planet in the Solar System, hot enough to melt lead!',
      'Venus is the brightest natural object in Earth\'s night sky after the Moon.'
    ],
    atmosphere: [
      { gas: 'Carbon Dioxide', percentage: '96.5%' },
      { gas: 'Nitrogen', percentage: '3.5%' },
      { gas: 'Sulfur Dioxide', percentage: 'Trace' }
    ],
    structure: [
      { name: 'Crust', thickness: '30-50 km', composition: 'Basaltic Rock', color: '#8D6E63' },
      { name: 'Mantle', thickness: '3,000 km', composition: 'Rocky Silicates', color: '#A1887F' },
      { name: 'Core', thickness: '6,000 km', composition: 'Iron-Nickel Alloy', color: '#FFB74D' }
    ],
    color: '#E5A93B',
    accentColor: '#FFCC80',
    texturePattern: 'bands',
    orbitalSpeed: 0.015,
    sizeScale: 10,
    realSizeScale: 9.5
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    mass: '5.972 x 10^24 kg',
    gravity: 9.81,
    diameter: 12742,
    tempRange: '-89°C to 58°C',
    orbitalPeriod: '365.26 Days',
    rotationPeriod: '23.9 Hours',
    distanceFromSun: 1.0,
    realDistanceMillionKm: 149.6,
    moons: [
      { name: 'Luna', distance: 16, size: 2.2, speed: 0.08 }
    ],
    description: 'Our home planet, Earth, is the only place in the universe known to harbor life. It is the third planet from the Sun and the densest planet in the Solar System, covered 70% in liquid water oceans.',
    funFacts: [
      'Earth is the only planet not named after a mythological god.',
      'Our atmosphere protects us from incoming meteoroids, breaking them up before they can hit.',
      'Earth\'s magnetic field is generated by electric currents flowing in its molten core.'
    ],
    atmosphere: [
      { gas: 'Nitrogen', percentage: '78.1%' },
      { gas: 'Oxygen', percentage: '20.9%' },
      { gas: 'Argon', percentage: '0.9%' },
      { gas: 'Carbon Dioxide', percentage: '0.04%' }
    ],
    structure: [
      { name: 'Crust', thickness: '5-70 km', composition: 'Granite and Basalt', color: '#3E2723' },
      { name: 'Mantle', thickness: '2,890 km', composition: 'Silicates', color: '#D84315' },
      { name: 'Outer Core', thickness: '2,260 km', composition: 'Liquid Iron-Nickel', color: '#FF8F00' },
      { name: 'Inner Core', thickness: '1,220 km', composition: 'Solid Iron-Nickel', color: '#FFD54F' }
    ],
    color: '#4B96D7',
    accentColor: '#2E7D32',
    texturePattern: 'solid',
    orbitalSpeed: 0.01,
    sizeScale: 11,
    realSizeScale: 10.0
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    mass: '6.390 x 10^23 kg',
    gravity: 3.71,
    diameter: 6779,
    tempRange: '-143°C to 35°C',
    orbitalPeriod: '687 Days',
    rotationPeriod: '24.6 Hours',
    distanceFromSun: 1.52,
    realDistanceMillionKm: 227.9,
    moons: [
      { name: 'Phobos', distance: 12, size: 1.2, speed: 0.15 },
      { name: 'Deimos', distance: 18, size: 0.8, speed: 0.07 }
    ],
    description: 'Mars is a cold, dusty, desert world with a very thin carbon dioxide atmosphere. Known as the Red Planet due to iron oxide (rust) on its surface, it exhibits polar ice caps and massive inactive volcanoes.',
    funFacts: [
      'Mars is home to Olympus Mons, the largest volcano in the Solar System, which is three times the height of Mt. Everest.',
      'Mars has two tiny moons, Phobos and Deimos, which are thought to be captured asteroids.',
      'Liquid water cannot exist on the surface of Mars for long due to the low atmospheric pressure.'
    ],
    atmosphere: [
      { gas: 'Carbon Dioxide', percentage: '95.3%' },
      { gas: 'Nitrogen', percentage: '2.7%' },
      { gas: 'Argon', percentage: '1.6%' },
      { gas: 'Oxygen', percentage: '0.13%' }
    ],
    structure: [
      { name: 'Crust', thickness: '50 km', composition: 'Iron-rich Basalt', color: '#BF360C' },
      { name: 'Mantle', thickness: '1,600 km', composition: 'Silicate Rock', color: '#E65100' },
      { name: 'Core', thickness: '1,800 km', composition: 'Iron, Nickel, Sulfur', color: '#FFB300' }
    ],
    color: '#C65F43',
    accentColor: '#FF7043',
    texturePattern: 'rocky',
    orbitalSpeed: 0.008,
    sizeScale: 7.5,
    realSizeScale: 5.3
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    mass: '1.898 x 10^27 kg',
    gravity: 24.79,
    diameter: 139820,
    tempRange: '-108°C (Average)',
    orbitalPeriod: '11.86 Years',
    rotationPeriod: '9.9 Hours',
    distanceFromSun: 5.20,
    realDistanceMillionKm: 778.5,
    moons: [
      { name: 'Io', distance: 18, size: 2.0, speed: 0.12 },
      { name: 'Europa', distance: 23, size: 1.8, speed: 0.09 },
      { name: 'Ganymede', distance: 29, size: 2.5, speed: 0.06 },
      { name: 'Callisto', distance: 35, size: 2.2, speed: 0.04 }
    ],
    description: 'Jupiter is the giant of our solar system, twice as massive as all other planets combined. It is a gas giant primarily made of hydrogen and helium, featuring complex cloud stripes and the iconic Great Red Spot storm.',
    funFacts: [
      'The Great Red Spot is a giant hurricane-like storm bigger than Earth that has raged for hundreds of years.',
      'Jupiter rotates faster than any other planet, completing a full day in just under 10 hours.',
      'Jupiter acts as a giant cosmic vacuum cleaner, attracting asteroid impacts due to its incredible gravity.'
    ],
    atmosphere: [
      { gas: 'Hydrogen', percentage: '89.8%' },
      { gas: 'Helium', percentage: '10.2%' },
      { gas: 'Methane', percentage: '0.3%' },
      { gas: 'Ammonia', percentage: 'Trace' }
    ],
    structure: [
      { name: 'Atmosphere', thickness: '5,000 km', composition: 'Hydrogen and Helium Gas', color: '#b08b5c' },
      { name: 'Mantle', thickness: '40,000 km', composition: 'Liquid Metallic Hydrogen', color: '#966c3b' },
      { name: 'Core', thickness: '14,000 km', composition: 'Dense Rock and Exotic Ice', color: '#4a2c11' }
    ],
    color: '#D4A373',
    accentColor: '#A67C52',
    texturePattern: 'bands',
    orbitalSpeed: 0.004,
    sizeScale: 20,
    realSizeScale: 22.0
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    mass: '5.683 x 10^26 kg',
    gravity: 10.44,
    diameter: 116460,
    tempRange: '-139°C (Average)',
    orbitalPeriod: '29.45 Years',
    rotationPeriod: '10.7 Hours',
    distanceFromSun: 9.58,
    realDistanceMillionKm: 1434.0,
    moons: [
      { name: 'Titan', distance: 25, size: 2.6, speed: 0.07 },
      { name: 'Enceladus', distance: 15, size: 1.4, speed: 0.14 },
      { name: 'Rhea', distance: 19, size: 1.6, speed: 0.10 },
      { name: 'Mimas', distance: 11, size: 1.1, speed: 0.20 }
    ],
    description: 'Adorned with a dazzling, complex system of icy rings, Saturn is a unique jewel in our solar system. It is a massive gas giant, and has the lowest density of all planets—it could float in a massive bathtub!',
    funFacts: [
      'Saturn\'s beautiful rings are made of billions of chunks of ice, dust, and rock, ranging from tiny dust grains to house-sized boulders.',
      'Saturn has over 140 moons, including Titan, the only moon in the solar system with a substantial atmosphere and liquid methane lakes.',
      'Saturn\'s winds can reach a blistering 1,800 kilometers per hour.'
    ],
    atmosphere: [
      { gas: 'Hydrogen', percentage: '96.3%' },
      { gas: 'Helium', percentage: '3.2%' },
      { gas: 'Methane', percentage: '0.4%' }
    ],
    structure: [
      { name: 'Atmosphere', thickness: '1,000 km', composition: 'Hydrogen/Helium Gas', color: '#E0CC99' },
      { name: 'Mantle', thickness: '30,000 km', composition: 'Liquid Metallic Hydrogen', color: '#C2AD70' },
      { name: 'Core', thickness: '10,000 km', composition: 'Hot Rock and Iron Core', color: '#736132' }
    ],
    color: '#E2CA90',
    accentColor: '#CBB26A',
    texturePattern: 'bands',
    ringColor: '#DFCCA0',
    ringRadiusInner: 1.4,
    ringRadiusOuter: 2.5,
    orbitalSpeed: 0.002,
    sizeScale: 17,
    realSizeScale: 18.0
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    mass: '8.681 x 10^25 kg',
    gravity: 8.69,
    diameter: 50724,
    tempRange: '-224°C (Average)',
    orbitalPeriod: '84 Years',
    rotationPeriod: '17.2 Hours (Retrograde)',
    distanceFromSun: 19.20,
    realDistanceMillionKm: 2871.0,
    moons: [
      { name: 'Titania', distance: 18, size: 1.8, speed: 0.09 },
      { name: 'Oberon', distance: 22, size: 1.6, speed: 0.07 },
      { name: 'Ariel', distance: 14, size: 1.4, speed: 0.12 },
      { name: 'Umbriel', distance: 16, size: 1.3, speed: 0.11 }
    ],
    description: 'Uranus is the seventh planet from the Sun and an ice giant. It has a beautiful blue-green color due to atmospheric methane gas. Exceedingly unique, it rotates sideways—literally rolling on its orbital plane.',
    funFacts: [
      'Uranus features an extreme 98-degree axial tilt, meaning its North and South poles face the Sun directly, leading to 21-year-long seasons.',
      'Uranus was the first planet discovered with a telescope, by astronomer William Herschel in 1781.',
      'Uranus is the coldest planet in the Solar System, with atmospheric temperatures plunging to -224.2°C.'
    ],
    atmosphere: [
      { gas: 'Hydrogen', percentage: '82.5%' },
      { gas: 'Helium', percentage: '15.2%' },
      { gas: 'Methane', percentage: '2.3%' }
    ],
    structure: [
      { name: 'Atmosphere', thickness: '5,000 km', composition: 'Hydrogen, Helium, Methane', color: '#A0D3E8' },
      { name: 'Mantle', thickness: '18,000 km', composition: 'Water, Ammonia, Methane Ices', color: '#5C9EBE' },
      { name: 'Core', thickness: '2,500 km', composition: 'Silicates and Iron-Nickel Rock', color: '#3A5E73' }
    ],
    color: '#7EC4CF',
    accentColor: '#96E0EC',
    texturePattern: 'solid',
    ringColor: '#A1BFC4',
    ringRadiusInner: 1.25,
    ringRadiusOuter: 1.35,
    orbitalSpeed: 0.001,
    sizeScale: 14,
    realSizeScale: 11.5
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    mass: '1.024 x 10^26 kg',
    gravity: 11.15,
    diameter: 49244,
    tempRange: '-218°C (Average)',
    orbitalPeriod: '164.8 Years',
    rotationPeriod: '16.1 Hours',
    distanceFromSun: 30.05,
    realDistanceMillionKm: 4495.0,
    moons: [
      { name: 'Triton', distance: 16, size: 2.1, speed: -0.10 }, // retrograde moon!
      { name: 'Proteus', distance: 11, size: 1.3, speed: 0.16 },
      { name: 'Nereid', distance: 22, size: 1.1, speed: 0.03 }
    ],
    description: 'Neptune is the eighth and most distant major planet orbiting our Sun. Dark, cold, and whipped by supersonic winds, it is an ice giant of brilliant cobalt color, possessing the fastest winds in the Solar System.',
    funFacts: [
      'Neptune\'s supersonic winds blow up to 2,100 kilometers per hour, twice as fast as commercial jet planes!',
      'Neptune\'s largest moon, Triton, orbits the planet in the opposite direction of Neptune\'s rotation (retrograde orbit).',
      'Because of dwarf planet Pluto\'s elliptical orbit, Pluto is occasionally closer to the Sun than Neptune!'
    ],
    atmosphere: [
      { gas: 'Hydrogen', percentage: '80.0%' },
      { gas: 'Helium', percentage: '19.0%' },
      { gas: 'Methane', percentage: '1.5%' }
    ],
    structure: [
      { name: 'Atmosphere', thickness: '5,000 km', composition: 'Hydrogen, Helium, Methane', color: '#4484D4' },
      { name: 'Mantle', thickness: '17,500 km', composition: 'Water, Ammonia, Methane Ices', color: '#2752A1' },
      { name: 'Core', thickness: '2,500 km', composition: 'Rocky Silicate Core', color: '#102554' }
    ],
    color: '#345EB5',
    accentColor: '#5E8EF5',
    texturePattern: 'bands',
    ringColor: '#4A6FA8',
    ringRadiusInner: 1.25,
    ringRadiusOuter: 1.35,
    orbitalSpeed: 0.0006,
    sizeScale: 13.5,
    realSizeScale: 11.2
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'dwarf',
    mass: '1.303 x 10^22 kg',
    gravity: 0.62,
    diameter: 2376,
    tempRange: '-229°C average',
    orbitalPeriod: '248 Years',
    rotationPeriod: '6.4 Days',
    distanceFromSun: 39.48,
    realDistanceMillionKm: 5906.0,
    moons: [
      { name: 'Charon', distance: 12, size: 1.5, speed: 0.05 }
    ],
    description: 'Once considered the ninth planet, Pluto was reclassified as a dwarf planet in 2006. It is an icy, dynamic world featuring a prominent white heart-shaped nitrogen glacier named Tombaugh Regio.',
    funFacts: [
      'Pluto has a giant glacier called Tombaugh Regio which is shaped like a giant heart and consists of nitrogen ice.',
      'Pluto comprises almost one-third liquid water, which is three times more water than all of Earth\'s oceans combined!',
      'Pluto and its largest moon Charon form a binary system because Charon is so large that they orbit a center of mass outside Pluto.'
    ],
    atmosphere: [
      { gas: 'Nitrogen', percentage: '99.0%' },
      { gas: 'Methane', percentage: '0.9%' },
      { gas: 'Carbon Monoxide', percentage: '0.1%' }
    ],
    structure: [
      { name: 'Crust', thickness: '100 km', composition: 'Nitrogen and Water Ice', color: '#D2B48C' },
      { name: 'Mantle', thickness: '250 km', composition: 'Water Ice Rock', color: '#8FBC8F' },
      { name: 'Core', thickness: '830 km', composition: 'Silicates and Metal core', color: '#696969' }
    ],
    color: '#C6A582',
    accentColor: '#E8DED3',
    texturePattern: 'rocky',
    orbitalSpeed: 0.0004,
    sizeScale: 4.5,
    realSizeScale: 2.0
  }
];
